version: '3'
services:
  chatbot-sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-sandbox
    environment:
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
    deploy:
      resources:
        limits:
          memory: 8g
    volumes:
      - .:/app